

services:
  server:
    build:
      context: ./server
      target: dev
    container_name: lms-server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/src/config/config.env
    environment:
      - PORT=8000
      - CLIENT_URL=http://localhost:3000

  client:
    build:
      context: ./client
      target: dev
    container_name: lms-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./client/.env
    environment:
      - SERVER_URL=http://server:8000
      - NEXT_PUBLIC_SERVER_URL=http://localhost:8000
    depends_on:
      - server
